import { Providers } from '@/components/lib/Provider';
import './globals.scss';
import type { Metadata } from 'next';
import AuthManager from '../components/Auth/AuthManager';

export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthManager>{children}</AuthManager>
        </Providers>
      </body>
    </html>
  );
}
