#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

COMMIT_PATTERN="^IMO-[1-9][0-9]*:[[:space:]]?.*\.$"

msg=$(cat .git/COMMIT_EDITMSG | sed '/^#.*/d')

echo "Debug: Commit message is: $msg"
if ! echo "$msg" | grep -qE "$COMMIT_PATTERN"; then
  echo "Debug: Commit message does not match pattern."
  echo -e "Error commit message: $msg does not follow the conventional commit standard, e.g.  'IMO-1234: Play the commit game.' "
  false
fi
 
# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

# Check tests with jest
yarn test ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Run your tester 🔨❌
          Run yarn test, add changes and try commit again.';
    false;
)

yarn format
 
echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
npx lint-staged