#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

COMMIT_PATTERN = '(^IMO-[1-9][0-9]*:\s?.*\.$)'

msg=$(cat $1 | sed '/^#.*/d')
if ! [[ "$msg" =~ $PATTERN_COMMITS ]]; then
  echo -e "\x1b[31mError commit message:\x1b[0m \x1b[33m"$msg"\x1b[0m does not follow conventional commit standard, e.g \x1b[33m 'IMO-1234: Play the commit game.' \x1b[33m"
  exit 1;
fi
 
# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

# Check tests with jest
yarn test ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Run your tester 🔨❌
          Run yarn test, add changes and try commit again.';
    false;
)

 
echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
npx lint-staged